# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----
require 'ipaddr'

# ---- original file header ----
#
# @summary
#   Summarise what the function does here
#
Puppet::Functions.create_function(:'reverse_tail') do
  # @param args
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :args
  end


  def default_impl(*args)
    
    begin
      dns=IPAddr.new(args[0]).mask(args[1]).reverse.split('.').collect {|x| x unless x == '0'}.compact.join('.')
      IPAddr.new(args[0]).reverse.sub(dns,'').gsub(/\.$/,'')
    rescue
      raise "Unable to reverse tail '#{args[0]}/#{args[1]}'"
    end
  
  end
end
